font_family		GeistMono Nerd Font
font_size		12

disable_ligatures	never

shell 			zsh
shell_integratoin	no-cursor

cursor_shape		block

url_color #e9eaed
url_style curly

remeber_window_size	no
initial_window_width 	78c
initial_window_height	23c
window_padding_width	30
cursor_blink_interval 	0

background_opacity 	0.50
confirm_os_window_close	0

sync_to_monitor		no

